name: Bug Report
description: Reporta un bug o problema en el paquete
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar este bug. Por favor llena la siguiente información para ayudarnos a resolverlo.

  - type: textarea
    id: description
    attributes:
      label: Descripción del bug
      description: Una descripción clara y concisa del problema
      placeholder: Describe qué sucedió...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Pasos para reproducir el comportamiento
      placeholder: |
        1. Importa el paquete
        2. Llama al método '...'
        3. Ve el error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: Describe qué esperabas que sucediera
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento actual
      description: Describe qué sucedió en realidad
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Código de ejemplo
      description: Si es aplicable, agrega código que reproduzca el problema
      render: dart

  - type: textarea
    id: environment
    attributes:
      label: Información del entorno
      description: |
        Proporciona información sobre tu entorno de desarrollo
      placeholder: |
        - OS: [ej. iOS, Android, macOS, Windows, Linux]
        - Flutter version: [ejecuta `flutter --version`]
        - Dart version: 
        - Package version: [versión de fakestore_fase3_mandrade]
        - Device: [si es aplicable]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Información adicional
      description: Cualquier otra información que pueda ser útil